### ISSUE TITLE
Implement HTTP-Server with TCP - connection

### ISSUE THREAD

**Issue by PalmerEldritch** [kth-ii1302-vt22-group-3/HTTP#1]
### SubTasks
- [x] - [ ] Choose web socket framework
- [x] Host on locally or on heroku?
- [x] Establish New Repo for server code
- [x] Install framework on repo
- [x] Implement the Server 

### Acceptance Criteria
- [x] Stabile established server connection between hardware and server.
- [x] Can show Log/test data
